version: "2.4"

services:
  darwinia_scan: &app_base
    init: true
    build: .
    image: 'scan/darwinia_end'
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASS: 'hello'
      MYSQL_DB: 'darwinia-scan'
      REDIS_ADDR: redis:6379
      GRPC_PYTHON_HOST: darwinia-tools
      GRPC_PYTHON_PORT: 50051
      CHAIN_WS_ENDPOINT: 'wss://crayfish.darwinia.network/'
      LOG_DIR: '../log'
      ES_ENABLE: 'false'
      DEPLOY_ENV: 'prod'
      NETWORK_NODE: 'darwinia'
    env_file: .env
    networks:
      - app_net
  darwinia-daemon:
    <<: *app_base
    image: 'scan/darwinia_end'
    container_name: 'darwinia-daemon'
    ports: []
    command: ["python","run.py","substrate"]

networks:
  app_net:
    external: true
