version: "2.4"

services:
  kusama-scan: &app_base
    init: true
    build: .
    image: 'scan/kusama_end'
    environment:
      MYSQL_HOST: mysql
      MYSQL_PASS: 'hello'
      MYSQL_DB: 'kusama-scan'
      REDIS_ADDR: redis:6379
      GRPC_PYTHON_HOST: kusama-tools
      GRPC_PYTHON_PORT: 50051
      CHAIN_WS_ENDPOINT: 'wss://canary-5.kusama.network/'
      LOG_DIR: '../log'
      ES_ENABLE: 'false'
      DEPLOY_ENV: 'prod'
      NETWORK_NODE: 'kusama'
      MAIL_APPKEY: ''
    networks:
      - app_net
  kusama-daemon:
    <<: *app_base
    image: 'scan/kusama_end'
    ports: []
    command: ["python","run.py","substrate"]

networks:
  app_net:
    external: true
